### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by mhamaril** [vuorenkoski/tsoha-photos#1]
Sovelluksen sisäänkirjautuminen toimii niin kuin pitää. Jos syöttää rekisteröimättömän käyttäjän niin siitä tulee ilmoitus että käyttäjää ei ole olemassa, jos syöttää oikean käyttäjän, mutta väärän salasanan niin virhe ilmoitus on että väärä salasana. Tässä ei ole minun mielestä muuta parannettavaa kuin antaisin mielummin epämääräisen virheilmoituksen kuten "käyttäjää ei ole olemassa tai väärä salasana". Silloin ilkeillä tahoilla on hieman hankalampaa arvata kirjautumistunnuksia kun ei tiedetä kumpi on väärin.

Etusivun toiminnallisuudet:
Katsele ja hallinnoi omia kuvia
-toimii niinkuin pitää
Katsele muiden käyttäjien kuvia
-näyttäisi toimivan, mutta yksi kuva on "rikki"
Lataa lisää kuvia
Hyvää että ei anna ladata vääriä tiedostoja. Kuvan lataus onnistui. Valikosta voi valita kuville kuvaajan, avainsanoja, henkilöitä, antaa katseluoikeuksia ja antaa kuvalle paikkatiedon. Luulin että nämä valitaan kiinteästä valikosta joten en tajunnut että näihin voi itse lisätä omia avainsanoja tai henkilöitä. Myöskään en löytänyt omaa nimeäni valittavien listalta, joten korjaisin sovellusta siten että siinä olisi tarkempi ohje. Joitain kuvia ladattaessa tuli "Internal Server Error". Ilmeisesti jos kuva on liian pieni niin sen lataus ei onnistu.
Hallinnoi paikkoja
Tässä voi muokata paikan tietoja, jotka on valokuvien latauksen yhteydessä syötetty tietokantaan, mutta niitä ei voi tästä lisätä sinne.

Ominaisuudet toimivat niinkuin piti, mutta en vain aluksi ymmärtänyt miten sitä piti käyttää. 

Koodista ei ole kauheasti kommentoitavaa. Se näyttää selkeältä ja kaikki toiminnot on tehty omiksi funktioiksi. Ehkä voisi eriyttää app.py tiedostosta kaikki @app.routet omaan routes.py tiedostoon kuten esimerkissä. Ei se tosin minun mielestä selkeyteen vaikuta. Kaiken kaikkiaan hyvin tehty sovellus. Vielä kun ulkoasun parantelee esim. bootstrapillä niin tästä tulee hyvä.

**Comment by vuorenkoski** [comment]
- Lisätty käyttöohje
- Kuvaan lataamiseen lisättiin tarkistus onko exif data ok. Tämän puute aiheutti kaatumisen
